### ISSUE TITLE
Favorites label as optional field

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/lunaria#145]
I feel the label should be optional

_Originally posted by @KillariDev in https://github.com/DarkFlorist/lunaria/pull/139#discussion_r1227713818_

**Comment by jubalm** [comment]
Create a fallback Label and make the form optional for the user.

- fallback format: {amount} {token_code}

**Comment by MicahZoltu** [comment]
I would rather have the "fallback" just be an empty string.  We already have amount and token symbol on the line below the label so a fallback of `{amount} {symbol}` would be redundant.
