### ISSUE TITLE
Transaction Balance Details

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/lunaria#149]
https://github.com/DarkFlorist/lunaria/blob/141defc28b8dd67d48eecbbeafafc7b8460b6831/app/ts/components/TransactionPage/TransactionDetails.tsx#L157-L185

In the Transaction Details page it has a field for `Balance Before Transaction`.  There are a couple problems with this:
1. It is actually Balance After Transaction.
2. It is actually Current Balance.

At a minimum, the text should be changed to say `After`.  However, if we want to show balance before/after a particular transaction then we will need to do notably more work to achieve this.
1. Figure out which block the transaction showed up in.
2. Query for account's balance for the previous block.
3. Query for account's balance for the block the transaction was in.
4. Store both of these values in local storage along with other transaction details because querying old blocks may not be possible long after the transaction is mined.
5. Present data from local storage, don't re-query every time the user loads the transaction details.

**Comment by jubalm** [comment]
Remove the component
