### ISSUE TITLE
Lunaria shows that I sent ETH NaN days ago

### ISSUE THREAD

**Issue by KillariDev** [DarkFlorist/lunaria#156]
![image](https://github.com/DarkFlorist/lunaria/assets/13102010/d8f635f7-a7aa-4c7c-b033-816f4019ec08)

**Comment by KillariDev** [comment]
it also doesn't show where I sent funds

**Comment by jubalm** [comment]
this should be fixed with https://github.com/DarkFlorist/lunaria/pull/147/files. the tab in the screenshot may have been opened prior to the fix and still has the old session

**Comment by jubalm** [comment]
Reopened as this was encountered again around 7/11
