### ISSUE TITLE
Improve error presentation to user.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/lunaria#169]
![image](https://github.com/DarkFlorist/lunaria/assets/886059/dfb832db-47e4-486a-93cf-04d34d29df5d)

```
user rejected action (action="sendTransaction", reason="rejected", info={ "error": { "code": 4001, "data": { "request": { "method": "eth_sendTransaction", "params": [ { "data": "0xa9059cbb000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa9604500000000000000000000000000000000000000000000000000000f478e084000", "from": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045", "gas": "0x8ee2", "to": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984" } ] } }, "message": "ethers-user-denied: Interceptor Tx Signature: User denied transaction signature." }, "payload": { "id": 52, "jsonrpc": "2.0", "method": "eth_sendTransaction", "params": [ { "data": "0xa9059cbb000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa9604500000000000000000000000000000000000000000000000000000f478e084000", "from": "0xd8da6bf26964af9d7eed9e03e53415d37aa96045", "gas": "0x8ee2", "to": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984" } ] } }, code=ACTION_REJECTED, version=6.6.1)
```

We should parse the error and look for and handle well known error codes.  We should work with @KillariDev to ensure we at least support all of the Interceptor errors and present them to the user in a nice clean way.

We should still include the JSON, but perhaps hidden behind an Additional Details <details> section or something.

Note: this is relatively low priority.

**Comment by jubalm** [comment]
- if error is recognized, parse and show only message
- if error is not recognized present message and hide data with ability to expand data

**Comment by jubalm** [comment]
Closing with #210 having merged, which addresses this feature.
