### ISSUE TITLE
Improve UX on handling adding of custom tokens if wallet is not connected

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/lunaria#195]
Right now it would not make a lot of sense to add custom token if a user does not have an account connected as storage key is based on account address.

- [ ] prompt user to connect a wallet before showing add token facility

**Comment by KillariDev** [comment]
hmm, why storage is based on account address? I don't think this should be the case. User might be using lunaria with multiple accounts and they should not have different storage values
