### ISSUE TITLE
Treat addresses as bigints

### ISSUE THREAD

**Issue by jubalm** [DarkFlorist/lunaria#200]
this should be EthereumQuantity which you can get from interceptors wire types too

_Originally posted by @KillariDev in https://github.com/DarkFlorist/lunaria/pull/197#discussion_r1311229989_

**Comment by KillariDev** [comment]
for addresses we have EthereumAddress in wire-types in interceptor which is the type you can use

**Comment by KillariDev** [comment]
but that address is non-checksummed one, you might want to have one for checksummed one if thats what you are using in code

**Comment by jubalm** [comment]
closing this one as ethersjs already have handlers for hex string addresses and checks for checksum as well
