### ISSUE TITLE
404 when trying to get the token icon for Ether.

### ISSUE THREAD

**Issue by MicahZoltu** [DarkFlorist/lunaria#99]
```
get https://lunaria.dark.florist/js/components/Icon/Tokens/Ether.js net::ERR_ABORTED 404
```
```ts
// in ts/components/Icon/Tokens/index.tsx
const module = await import(path)
```

Separately, why are these images being imported dynamically via JS rather than just being referenced as `.svg`s?  Seems like you could just have the component be `<img src={path}/>` and store them on disk as SVGs.  Same question for everything in `Icon` folder it appears.

**Comment by jubalm** [comment]
There's a quick fix at the moment for the missing icon (invalid path) #101. Keeping this issue open since SVG handling would require #92 to complete first

**Comment by jubalm** [comment]
#115 image paths are now applied in new UI
